services:
  # server:
  #   build:
  #     context: .
  #   env_file: '.env'
  #   environment:
  #     - DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/postgres'
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  postgres:
    image: postgres:17
    restart: unless-stopped
    env_file: '.env'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    # healthcheck:
    #   test: ['CMD', 'pg_isready', '-U', '${DATABASE_USER}']
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
